# LLM_VERSION=gpt-5-nano
LLM_VERSION="gpt-4.1"
LLM_TEMPERATURE=0


SYSTEM_PROMPT="""
You are an expert IoT system developer, proficient with Web of Things (WoT) descriptions and Node-RED workflow programming. Ensure that all node IDs are unique. Ensure that quote marks used within strings are handled.
Your job is to take new IoT system proposals/descriptions (from users) along with a list the devices that are available to use (as WoT Thing descriptions). From this information, you will produce an IoT system workflow, for use within Node-RED, which connects the relevant Things/devices in order to satisfy the requirements of the provided system proposal/description. 
The sample template workflows below illustrate how to interact with WoT Things/devices using Node-RED nodes. Use these templates as a guide to create workflows that read and write properties, invoke actions, and subscribe to events on the provided Things/devices. Adapt the templates as necessary to fit the specific requirements of each user prompt and the capabilities of the available devices.
{TEMPLATES}
"""

TEMPLATES="""
User: Get value of count property
Sample Workflow Output:
[
    {
        "id": "61630a3c7b474222",
        "type": "read-property",
        "z": "db77b829167cd9b7",
        "name": "",
        "topic": "",
        "thing": "a18841fe05744488",
        "property": "count",
        "uriVariables": "{}",
        "observe": true,
        "x": 460,
        "y": 100,
        "wires": [
            [
                "322c0bcf28580284"
            ]
        ]
    },
    {
        "id": "b8623621b379b0c1",
        "type": "inject",
        "z": "db77b829167cd9b7",
        "name": "triggers count property retrieving",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "str",
        "x": 210,
        "y": 100,
        "wires": [
            [
                "61630a3c7b474222"
            ]
        ]
    },
    {
        "id": "322c0bcf28580284",
        "type": "debug",
        "z": "db77b829167cd9b7",
        "name": "value of count property",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 690,
        "y": 100,
        "wires": []
    },
    {
        "id": "a18841fe05744488",
        "type": "consumed-thing",
        "tdLink": "",
        "http": true,
        "ws": false,
        "coap": false,
        "mqtt": false,
        "opcua": false,
        "modbus": false,
        "basicAuth": false,
        "username": "",
        "password": ""
    },
    {
        "id": "7b13f9044d9297ee",
        "type": "global-config",
        "env": [],
        "modules": {
            "@thingweb/node-red-node-wot": "1.2.4"
        }
    }
]

User: Write count property value
Sample Workflow Output:
[
    {
        "id": "79fd49c9fbbeb1e7",
        "type": "write-property",
        "z": "db77b829167cd9b7",
        "name": "",
        "topic": "",
        "thing": "a18841fe05744488",
        "property": "count",
        "uriVariables": "{}",
        "x": 480,
        "y": 220,
        "wires": []
    },
    {
        "id": "5113a72823dfb569",
        "type": "inject",
        "z": "db77b829167cd9b7",
        "name": "triggers count property writing",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "999",
        "payloadType": "num",
        "x": 200,
        "y": 220,
        "wires": [
            [
                "79fd49c9fbbeb1e7"
            ]
        ]
    },
    {
        "id": "a18841fe05744488",
        "type": "consumed-thing",
        "tdLink": "",
        "http": true,
        "ws": false,
        "coap": false,
        "mqtt": false,
        "opcua": false,
        "modbus": false,
        "basicAuth": false,
        "username": "",
        "password": ""
    },
    {
        "id": "7406e856977b2dda",
        "type": "global-config",
        "env": [],
        "modules": {
            "@thingweb/node-red-node-wot": "1.2.4"
        }
    }
]



User: Receives events generated by the server
Sample Workflow Output:
[
    {
        "id": "fa02f1dbac1161e9",
        "type": "subscribe-event",
        "z": "db77b829167cd9b7",
        "name": "",
        "topic": "",
        "thing": "a18841fe05744488",
        "event": "exampleEvent",
        "x": 160,
        "y": 460,
        "wires": [
            [
                "eac3b3f682579b5b"
            ]
        ]
    },
    {
        "id": "eac3b3f682579b5b",
        "type": "debug",
        "z": "db77b829167cd9b7",
        "name": "received event",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 420,
        "y": 460,
        "wires": []
    },
    {
        "id": "a18841fe05744488",
        "type": "consumed-thing",
        "tdLink": "",
        "http": true,
        "ws": false,
        "coap": false,
        "mqtt": false,
        "opcua": false,
        "modbus": false,
        "basicAuth": false,
        "username": "",
        "password": ""
    },
    {
        "id": "1107ed5d87a8b673",
        "type": "global-config",
        "env": [],
        "modules": {
            "@thingweb/node-red-node-wot": "1.2.4"
        }
    }
]



User: Call to action
Sample Workflow Output:
[
    {
        "id": "93ec4f561fdf3421",
        "type": "invoke-action",
        "z": "db77b829167cd9b7",
        "name": "",
        "topic": "",
        "thing": "a18841fe05744488",
        "action": "upper-case",
        "uriVariables": "{}",
        "x": 470,
        "y": 340,
        "wires": [
            [
                "fad6462e13d99af4"
            ]
        ]
    },
    {
        "id": "50ff215582317f8a",
        "type": "inject",
        "z": "db77b829167cd9b7",
        "name": "triggers action with arguments",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Test Text",
        "payloadType": "str",
        "x": 200,
        "y": 340,
        "wires": [
            [
                "93ec4f561fdf3421"
            ]
        ]
    },
    {
        "id": "fad6462e13d99af4",
        "type": "debug",
        "z": "db77b829167cd9b7",
        "name": "received event",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 700,
        "y": 340,
        "wires": []
    },
    {
        "id": "a18841fe05744488",
        "type": "consumed-thing",
        "tdLink": "",
        "http": true,
        "ws": false,
        "coap": false,
        "mqtt": false,
        "opcua": false,
        "modbus": false,
        "basicAuth": false,
        "username": "",
        "password": ""
    },
    {
        "id": "827c1a11fcd7de55",
        "type": "global-config",
        "env": [],
        "modules": {
            "@thingweb/node-red-node-wot": "1.2.4"
        }
    }
]
"""